### ISSUE TITLE
Usermanagement.json file missing

### ISSUE THREAD

**Issue by faru1** [rozek/node-red-user-management-example#1]
Hi. Love your work.
Could you please update the link for usermanagement.json. as its not located in the main branch niether in the readme link.
Thanks

**Comment by rozek** [comment]
Hello,

sorry for the late response, but I was infected with the SARS-CoV-2 virus and had to cure myself first.

Where did you find a link for `usermanagement.json`? There shouldn't be one, nowhere.

Or did you have s.th. else in mind?

With greetings from Germany,

Andreas Rozek

**Comment by bmarolleau** [comment]
Hi @rozek  , same issue. UserManagement.json flow mentioned in README.md  is missing.  
thx for your help,

**Comment by rozek** [comment]
Oh, I see: the flow itself got lost. Ok let me see where I can find a backup...

**Comment by rozek** [comment]
I've just uploaded the missing flow - thank you very much for your notice!

**Comment by bmarolleau** [comment]
thanks @rozek !!
